#!/bin/bash

set -e

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)  
repoName=${IMAGE_NAME:0:tagStart-1}

# Tag and push image as latest
docker tag $IMAGE_NAME ${repoName}:latest
docker push ${repoName}:latest
